//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MApp.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public System.DateTime DateTime { get; set; }
        public int IssueId { get; set; }
        public int UserId { get; set; }
        public string Type { get; set; }
        public string Text { get; set; }
        public bool Anonymous { get; set; }
    
        public virtual Issue Issue { get; set; }
        public virtual User User { get; set; }
    }
}
