//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MApp.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApplicationDBEntities : DbContext
    {
        public ApplicationDBEntities()
            : base("name=ApplicationDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessRight> AccessRight { get; set; }
        public virtual DbSet<Alternative> Alternative { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<Criterion> Criterion { get; set; }
        public virtual DbSet<CriterionWeight> CriterionWeight { get; set; }
        public virtual DbSet<Decision> Decision { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<HAccessRight> HAccessRight { get; set; }
        public virtual DbSet<HAlternative> HAlternative { get; set; }
        public virtual DbSet<HCriterion> HCriterion { get; set; }
        public virtual DbSet<HDecision> HDecision { get; set; }
        public virtual DbSet<HIssue> HIssue { get; set; }
        public virtual DbSet<HReview> HReview { get; set; }
        public virtual DbSet<HTagIssue> HTagIssue { get; set; }
        public virtual DbSet<InformationRead> InformationRead { get; set; }
        public virtual DbSet<Issue> Issue { get; set; }
        public virtual DbSet<Notification> Notification { get; set; }
        public virtual DbSet<PairwiseComparisonAC> PairwiseComparisonAC { get; set; }
        public virtual DbSet<PairwiseComparisonCC> PairwiseComparisonCC { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Tag> Tag { get; set; }
        public virtual DbSet<TagIssue> TagIssue { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
