//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MApp.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDecision
    {
        public System.DateTime ChangeDate { get; set; }
        public int IssueId { get; set; }
        public int UserId { get; set; }
        public string Action { get; set; }
        public Nullable<int> AlternativeId { get; set; }
        public string Explanation { get; set; }
    
        public virtual Decision Decision { get; set; }
        public virtual User User { get; set; }
    }
}
