using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MApp.DA
{
    /// <summary>
    /// autogenerated db context class
    /// </summary>
    class MainDbContext : DbContext
    {
        public MainDbContext() : base("name=ApplicationDBEntities")
        {
        }
    }
}
