//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MApp.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class PairwiseComparisonCC
    {
        public int CriterionLeft { get; set; }
        public int CriterionRight { get; set; }
        public int UserId { get; set; }
        public double Value { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual Criterion Criterion1 { get; set; }
        public virtual User User { get; set; }
    }
}
